export const TEMPLATES = [
  [
    'leemunroe-inlined',
    'https://raw.githubusercontent.com/leemunroe/responsive-html-email-template/master/email-inlined.html',
  ],
  [
    'mailgun-action',
    'https://raw.githubusercontent.com/mailgun/transactional-email-templates/master/templates/inlined/action.html',
  ],
  [
    'mailgun-alert',
    'https://raw.githubusercontent.com/mailgun/transactional-email-templates/master/templates/inlined/alert.html',
  ],
  [
    'mailgun-billing',
    'https://raw.githubusercontent.com/mailgun/transactional-email-templates/master/templates/inlined/billing.html',
  ],
  [
    'waypoint-banking-payout',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/banking-payout.html',
  ],
  [
    'waypoint-banking-refund-approved',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/banking-refund-approved.html',
  ],
  [
    'waypoint-banking-withdrawal',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/banking-withdrawal.html',
  ],
  [
    'waypoint-ecommerce-delivery',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/ecommerce-delivery-notification.html',
  ],
  [
    'waypoint-ecommerce-milestone-reward',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/ecommerce-milestone-reward.html',
  ],
  [
    'waypoint-ecommerce-new-order-receipt',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/ecommerce-new-order-receipt.html',
  ],
  [
    'waypoint-ecommerce-promo-code',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/ecommerce-promo-code.html',
  ],
  [
    'waypoint-ecommerce-reengagement',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/ecommerce-reengagement.html',
  ],
  [
    'waypoint-ecommerce-welcome',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/ecommerce-welcome.html',
  ],
  [
    'waypoint-marketplace-credit-expiring',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/marketplace-credit-expiring.html',
  ],
  [
    'waypoint-marketplace-first-listing-notification',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/marketplace-first-listing-notification.html',
  ],
  [
    'waypoint-marketplace-new-delivery',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/marketplace-new-delivery.html',
  ],
  [
    'waypoint-marketplace-qr',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/marketplace-qr-tickets.html',
  ],
  [
    'waypoint-marketplace-reservation-reminder',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/marketplace-reservation-reminder.html',
  ],
  [
    'waypoint-marketplace-respond-to-inquiry',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/marketplace-respond-to-inquiry.html',
  ],
  [
    'waypoint-marketplace-saved-search',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/marketplace-saved-search.html',
  ],
  [
    'waypoint-saas-accept-invite',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-accept-invite.html',
  ],
  [
    'waypoint-saas-app-store-links',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-app-store-links.html',
  ],
  [
    'waypoint-saas-credit-usage-report',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-credit-usage-report.html',
  ],
  [
    'waypoint-saas-download-ready',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-download-ready.html',
  ],
  [
    'waypoint-saas-first-time-watched',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-first-time-watched.html',
  ],
  [
    'waypoint-saas-milestone-next-steps',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-milestone-next-steps.html',
  ],
  [
    'waypoint-saas-otp',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-one-time-passcode-otp.html',
  ],
  [
    'waypoint-saas-password-changed',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-password-changed.html',
  ],
  [
    'waypoint-saas-payment-declined',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-payment-declined.html',
  ],
  [
    'waypoint-saas-reset-password',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-reset-password.html',
  ],
  [
    'waypoint-saas-receipt',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-subscription-receipt.html',
  ],
  [
    'waypoint-saas-trial-ends-soon',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-trial-ends-soon.html',
  ],
  [
    'waypoint-saas-weekly-metrics-report',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-weekly-metrics-report.html',
  ],
  [
    'waypoint-saas-welcome',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/saas-welcome.html',
  ],
  [
    'waypoint-social-new-comment',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/social-new-comment.html',
  ],
  [
    'waypoint-social-new-follower',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/social-new-follower.html',
  ],
  [
    'waypoint-social-post-metrics',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/social-post-metrics.html',
  ],
  [
    'waypoint-social-yearly-wrapped-report',
    'https://raw.githubusercontent.com/usewaypoint/responsive-transactional-email-templates/main/templates/social-yearly-wrapped-report.html',
  ],
  [
    'mailpace-welcome',
    'https://raw.githubusercontent.com/mailpace/templates/main/dist/welcome.html',
  ],
  [
    'mailpace-confirmation',
    'https://raw.githubusercontent.com/mailpace/templates/main/dist/confirmation.html',
  ],
  [
    'mailpace-password-reset',
    'https://raw.githubusercontent.com/mailpace/templates/main/dist/password_reset.html',
  ],
  [
    'mailpace-receipt',
    'https://raw.githubusercontent.com/mailpace/templates/main/dist/receipt.html',
  ],
  [
    'mailpace-security-alert',
    'https://raw.githubusercontent.com/mailpace/templates/main/dist/security_alert.html',
  ],
  [
    'mailpace-account-deleted',
    'https://raw.githubusercontent.com/mailpace/templates/main/dist/account_deleted.html',
  ],
  [
    'postmark-comment-notification',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/comment-notification/content.html',
  ],
  [
    'postmark-dunning',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/dunning/content.html',
  ],
  [
    'postmark-example',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/example/content.html',
  ],
  [
    'postmark-invoice',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/invoice/content.html',
  ],
  [
    'postmark-password-reset-help',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/password-reset-help/content.html',
  ],
  [
    'postmark-password-reset',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/password-reset/content.html',
  ],
  [
    'postmark-receipt',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/receipt/content.html',
  ],
  [
    'postmark-trial-expired',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/trial-expired/content.html',
  ],
  [
    'postmark-trial-expiring',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/trial-expiring/content.html',
  ],
  [
    'postmark-user-invitation',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/user-invitation/content.html',
  ],
  [
    'postmark-welcome',
    'https://raw.githubusercontent.com/ActiveCampaign/postmark-templates/main/templates/basic/welcome/content.html',
  ],
  [
    'mailersend-password-reminder',
    'https://raw.githubusercontent.com/mailersend/transactional-email-templates/main/01-%20Setting%20Up%20Account%20/password-reminder.html',
  ],
  [
    'mailersend-password-reminder-2',
    'https://raw.githubusercontent.com/mailersend/transactional-email-templates/main/01-%20Setting%20Up%20Account%20/password-reminder-2.html',
  ],
  [
    'mailersend-welcome-01',
    'https://raw.githubusercontent.com/mailersend/transactional-email-templates/main/01-%20Setting%20Up%20Account%20/welcome-email-01.html',
  ],
  [
    'mailersend-welcome-2',
    'https://raw.githubusercontent.com/mailersend/transactional-email-templates/main/01-%20Setting%20Up%20Account%20/welcome-email-2.html',
  ],
  [
    'mailersend-invoice',
    'https://raw.githubusercontent.com/mailersend/transactional-email-templates/main/02-%20Order%20Management%20/invoice.html',
  ],
  [
    'mailersend-invoice-2',
    'https://raw.githubusercontent.com/mailersend/transactional-email-templates/main/02-%20Order%20Management%20/invoice-2.html',
  ],
  [
    'mailersend-order-confirmation',
    'https://raw.githubusercontent.com/mailersend/transactional-email-templates/main/02-%20Order%20Management%20/order-confirmation.html',
  ],
  [
    'mailersend-feedback',
    'https://raw.githubusercontent.com/mailersend/transactional-email-templates/main/03-%20Keeping%20in%20Touch%20/feedback.html',
  ],
  [
    'mailersend-product-announcement',
    'https://raw.githubusercontent.com/mailersend/transactional-email-templates/main/03-%20Keeping%20in%20Touch%20/product-announcement.html',
  ],
  [
    'sendgrid-dynamic-receipt',
    'https://raw.githubusercontent.com/sendgrid/email-templates/master/dynamic-templates/receipt/receipt.html',
  ],
  [
    'sendgrid-call-to-action',
    'https://raw.githubusercontent.com/sendgrid/email-templates/master/dynamic-templates/transactional-actions/call_to_action.html',
  ],
  [
    'sendgrid-paste-password-reset',
    'https://raw.githubusercontent.com/sendgrid/email-templates/master/paste-templates/password-reset.html',
  ],
  [
    'sendgrid-paste-welcome',
    'https://raw.githubusercontent.com/sendgrid/email-templates/master/paste-templates/welcome.html',
  ],
  [
    'sendgrid-merriweather-receipt',
    'https://raw.githubusercontent.com/sendgrid/email-templates/master/merriweather-templates/receipt.html',
  ],
  [
    'sendgrid-merriweather-welcome',
    'https://raw.githubusercontent.com/sendgrid/email-templates/master/merriweather-templates/welcome.html',
  ],
  [
    'ckissi-welcome',
    'https://raw.githubusercontent.com/ckissi/responsive-html-email-templates/master/Welcome/welcome.html',
  ],
  [
    'ckissi-reset-password',
    'https://raw.githubusercontent.com/ckissi/responsive-html-email-templates/master/Reset%20password/reset-password.html',
  ],
  [
    'ckissi-confirm-email',
    'https://raw.githubusercontent.com/ckissi/responsive-html-email-templates/master/Confirm%20Email/confirm-email.html',
  ],
  [
    'ckissi-invoice',
    'https://raw.githubusercontent.com/ckissi/responsive-html-email-templates/master/Invoice/invoice.html',
  ],
  [
    'ckissi-trial-expired',
    'https://raw.githubusercontent.com/ckissi/responsive-html-email-templates/master/Trial%20Expired/trial-expired.html',
  ],
  [
    'davidamunga-welcome',
    'https://raw.githubusercontent.com/DavidAmunga/html-email-templates/master/welcome.html',
  ],
  [
    'davidamunga-reset-password',
    'https://raw.githubusercontent.com/DavidAmunga/html-email-templates/master/reset-password.html',
  ],
];
